name: Publish Angular Library to GitHub Packages

on:
  push:
    branches:
      - main
      - "v*.*.*"

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: https://npm.pkg.github.com/
          scope: '@msaadart'

      - name: Install Dependencies
        run: npm install

      - name: Build Angular Library
        run: npm run build shared

      - name: Publish to GitHub Packages
        run: npm publish dist/shared
        env:
          NODE_AUTH_TOKEN: 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
