name: Publish Angular Library to GitHub Packages

on:
  push:
    branches:
      - main
      - "v*.*.*"

permissions:
    contents: read
    packages: write

jobs:
  publish-gpr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: https://npm.pkg.github.com/
          scope: '@msaadart'
      - run: |
          curl -H "Authorization: Bearer $GITHUB_TOKEN" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/${{ github.repository }}
      - run: npm install
      - run: npm publish dist/shared
        env:
          NODE_AUTH_TOKEN: ${{secrets.TOKEN_ACCESS}}